--
-- PostgreSQL database dump
--

\restrict GEpGSYQopaFjHDvqYnXBOcBhPZPWqkNxPJaIMJf2KQOB5SjJLBX5fSDCBD6Zv3c

-- Dumped from database version 16.11
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: trip_bookings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trip_bookings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    number_of_seats integer NOT NULL,
    status character varying(255) NOT NULL,
    total_price double precision NOT NULL,
    trip_id bigint NOT NULL,
    user_id character varying(255) NOT NULL
);


ALTER TABLE public.trip_bookings OWNER TO postgres;

--
-- Name: trip_bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trip_bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trip_bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trips (
    id bigint NOT NULL,
    arrival_time timestamp(6) without time zone NOT NULL,
    available_seats integer NOT NULL,
    carrier character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    departure_time timestamp(6) without time zone NOT NULL,
    destination character varying(255) NOT NULL,
    origin character varying(255) NOT NULL,
    price double precision NOT NULL,
    transport_type character varying(255) NOT NULL
);


ALTER TABLE public.trips OWNER TO postgres;

--
-- Name: trips_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.trips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: trip_bookings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trip_bookings (id, created_at, number_of_seats, status, total_price, trip_id, user_id) FROM stdin;
\.


--
-- Data for Name: trips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.trips (id, arrival_time, available_seats, carrier, created_at, departure_time, destination, origin, price, transport_type) FROM stdin;
\.


--
-- Name: trip_bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trip_bookings_id_seq', 1, false);


--
-- Name: trips_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.trips_id_seq', 1, false);


--
-- Name: trip_bookings trip_bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trip_bookings
    ADD CONSTRAINT trip_bookings_pkey PRIMARY KEY (id);


--
-- Name: trips trips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.trips
    ADD CONSTRAINT trips_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict GEpGSYQopaFjHDvqYnXBOcBhPZPWqkNxPJaIMJf2KQOB5SjJLBX5fSDCBD6Zv3c

